/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cbm.crm.panels;

import com.cbm.crm.Thereness;
import com.cbm.crm.entity.Role;
import com.cbm.crm.entity.client.RoleClient;
import com.cbm.crm.strings.String_Constants;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Sakkie
 */
public class JRolePanel extends javax.swing.JPanel {

    public ArrayList<Role> roles = new ArrayList<>();
    public Role role = new Role();
    public boolean dbCrud = false;
    /**
     * Creates new form JRolePanel
     */
    public JRolePanel() {
        initComponents();
        
        clear();
    }
    
    public void clear() {
        clearText();
        cmbRoleList.setSelectedIndex(0);
        
    }
    
    public void clearText() {
        //role = null;
        txtRoleName.setText("{none}");
        txtRoleDescription.setText("{none}");
        txtRoleName.setEditable(false);
        txtRoleDescription.setEditable(false);
        btnSaveRole.setText("New");
    }
    
    public void fillCmb() {
        for(int a=0; a<roles.size(); a++) {
            cmbRoleList.addItem(roles.get(a).getRoleName());
        }
    }

    public boolean isDbCrud() {
        return dbCrud;
    }

    public void setDbCrud(boolean dbCrud) {
        pnlNewRole.setVisible(dbCrud);
        
        txtRoleName.setEditable(dbCrud);
        txtRoleDescription.setEditable(dbCrud);
        
        this.dbCrud = dbCrud;
    }
    
    /*public Role getRole(Role r) {
        r.setRoleId(Thereness.be().roles.get(Thereness.be().current[3]).getRoleId());
        return r;
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbRoleList = new javax.swing.JComboBox<>();
        btnRoleListRefresh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRoleName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRoleDescription = new javax.swing.JTextArea();
        pnlNewRole = new javax.swing.JPanel();
        btnDeleteRole = new javax.swing.JButton();
        btnSaveRole = new javax.swing.JButton();
        btnClearRole = new javax.swing.JButton();

        cmbRoleList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        cmbRoleList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbRoleListItemStateChanged(evt);
            }
        });

        btnRoleListRefresh.setText("Refresh");

        jLabel1.setText("Name");

        jLabel2.setText("Description");

        txtRoleName.setEditable(false);

        txtRoleDescription.setEditable(false);
        txtRoleDescription.setColumns(20);
        txtRoleDescription.setRows(5);
        jScrollPane1.setViewportView(txtRoleDescription);

        btnDeleteRole.setText("Delete");
        btnDeleteRole.setEnabled(false);

        btnSaveRole.setText("Save");
        btnSaveRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRoleActionPerformed(evt);
            }
        });

        btnClearRole.setText("Clear");
        btnClearRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearRoleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNewRoleLayout = new javax.swing.GroupLayout(pnlNewRole);
        pnlNewRole.setLayout(pnlNewRoleLayout);
        pnlNewRoleLayout.setHorizontalGroup(
            pnlNewRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewRoleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSaveRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClearRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlNewRoleLayout.setVerticalGroup(
            pnlNewRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewRoleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNewRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveRole)
                    .addComponent(btnDeleteRole)
                    .addComponent(btnClearRole))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRoleName)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(pnlNewRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRoleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlNewRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbRoleList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRoleListRefresh)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRoleList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoleListRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRoleListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbRoleListItemStateChanged
        //Thereness.be().current[3] = cmbRoleList.getSelectedIndex();
        if(cmbRoleList.getSelectedIndex()==0) {
            clearText();
            //role = null;
            //txtRoleName.setText("{none}");
            //txtRoleDescription.setText("{none}");
            //btnSaveRole.setText("New");
        } else if(roles.size()==cmbRoleList.getItemCount()-1&&cmbRoleList.getSelectedIndex()>0) {
            //role = roles.get(cmbRoleList.getSelectedIndex()-1);
            txtRoleName.setText(roles.get(cmbRoleList.getSelectedIndex()-1).getRoleName());
            txtRoleDescription.setText(roles.get(cmbRoleList.getSelectedIndex()-1).getDescription());
            //if()
            btnSaveRole.setText("Update");
        }
    }//GEN-LAST:event_cmbRoleListItemStateChanged

    private void btnSaveRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRoleActionPerformed
        try {
            if(btnSaveRole.getText().equals("Save")) {
                if(!txtRoleName.getText().isEmpty()&&!txtRoleDescription.getText().isEmpty()) {
                    RoleClient client = new RoleClient();
                    Role nR = new Role();
                    nR.setRoleName(txtRoleName.getText());
                    nR.setDescription(txtRoleDescription.getText());
                    client.create_JSON(nR);
                    client.close();
                } else {
                    JOptionPane.showMessageDialog(null, String_Constants.FILL_FIELDS+":\nName and Description");
                }
            } else if(btnSaveRole.getText().equals("Update")) {
                if(!txtRoleName.getText().isEmpty()&&!txtRoleDescription.getText().isEmpty()) {
                    RoleClient client = new RoleClient();
                    Role nR = new Role();
                    nR.setRoleName(txtRoleName.getText());
                    nR.setDescription(txtRoleDescription.getText());
                    client.edit_JSON(nR, role.getRoleId()+"");
                    client.close();
                } else {
                    JOptionPane.showMessageDialog(null, String_Constants.FILL_FIELDS+":\nName and Description");
                }
            } else if(btnSaveRole.getText().equals("New")) {
                //role = new com.cbm.crm.entity.Role();
                txtRoleName.setText("");
                txtRoleDescription.setText("");
                txtRoleName.setEditable(true);
                txtRoleDescription.setEditable(true);
                btnSaveRole.setText("Save");
            }
            
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveRoleActionPerformed

    private void btnClearRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearRoleActionPerformed
        clear();
        //cmbRoleList.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearRoleActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearRole;
    private javax.swing.JButton btnDeleteRole;
    private javax.swing.JButton btnRoleListRefresh;
    private javax.swing.JButton btnSaveRole;
    private javax.swing.JComboBox<String> cmbRoleList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlNewRole;
    private javax.swing.JTextArea txtRoleDescription;
    private javax.swing.JTextField txtRoleName;
    // End of variables declaration//GEN-END:variables
}
